export enum CodigosDeErro {
  ENTRADA_INVALIDA = 'ENTRADA_INVALIDA',
  NAO_AUTORIZADO = 'NAO_AUTORIZADO',
  ACESSO_NEGADO = 'ACESSO_NEGADO',
  CONFLITO = 'CONFLITO',
  NAO_ENCONTRADO = 'NAO_ENCONTRADO',
  DESEQUILIBRIO_CONTABIL = 'DESEQUILIBRIO_CONTABIL',
  ERRO_BANCO_DE_DADOS = 'ERRO_BANCO_DE_DADOS',
  ERRO_MAPEAMENTO = 'ERRO_MAPEAMENTO',
  ERRO_INTERNO = 'ERRO_INTERNO'
  
}